spring.application.name=Module2
#debug=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:D:/Desktop/Java/Anuj_Bhaiya_Spring_Boot/Module2-SpringBott_MVC_RESTFUL_APIS
spring.datasource.username=harshdeep
spring.datasource.password=Harshdeep@2003
spring.jpa.hibernate.ddl-auto=create
